### ISSUE TITLE
Notification tags don't work

### ISSUE THREAD

**Issue by mikhailperemitko** [pushbots/android-sdk-example#1]
I've tried to uncomment following `MainActivity` code:
`try{
            JSONArray tags = new JSONArray();
            tags.put("test1");
            tags.put("test6");
            JSONObject json = new JSONObject();
            json.put("alias", "test");
            json.put("tags_add", tags);
            Pushbots.sharedInstance().update(json);
        } catch (JSONException e) {
            e.printStackTrace();
        }`
Expected to receive only notifications matching these tags, but I still receive all notifications. For example, by tag "231242". At the same time, I can see, that my tag configuration was updated. 
![screen shot 2018-02-06 at 12 20 17](https://user-images.githubusercontent.com/32171838/35854141-428b94fc-0b38-11e8-99f6-8dd9de06d5cd.png)

**Comment by amrsobhy** [comment]
Can you please share your sending request? Are you sending from the dashboard or API?

**Comment by mikhailperemitko** [comment]
I'm sending from the dashboard this way
![screen shot 2018-02-06 at 12 44 04](https://user-images.githubusercontent.com/32171838/35855329-89e5bdf2-0b3b-11e8-938c-fcb8abb327e0.png)

**Comment by amrsobhy** [comment]
Have you pressed enter or comma after adding the tag?

**Comment by mikhailperemitko** [comment]
No, I have not, only tag

**Comment by mikhailperemitko** [comment]
Do you have any ideas else?

**Comment by amrsobhy** [comment]
![sample](https://user-images.githubusercontent.com/6784122/36029289-46585e10-0dab-11e8-9277-fdee9933fa16.gif)

**Comment by mikhailperemitko** [comment]
Thank you for explanation.

**Comment by mikhailperemitko** [comment]
Can you, please, add some button to make it more intuitive to add tags?

**Comment by amrsobhy** [comment]
Yes we will fix it.
